# Define system parameters

database:
    drivername:   mysql
    connectionpool: 100       # mysql连接池大小
    address:
        host:   127.0.0.1
        port:   3307
    dbname:   crawlergo
    user:   crawler
    passwd:   crawler




